transparency = 150
ui_scale = 2.2
show_bots = true
window_size = [
    1920.0,
    1080.0,
]
anchor = "CenterRight"
monitor_index = 0
hotkey_kb = "Backspace"
hotkey_ctrl = "Select"
hotkey_settings = "F1"
hotkey_toggle = false
show_stats = true
show_teammate_boost = false
teammate_boost_offset = 180.0
teammate_boost_horizontal_offset = 110.0
teammate_hud_scale = 2.2
teammate_boost_display = "Bars"
rocket_league_path = ""
alpha_boost_enabled = false
session_overlay_enabled = false
session_overlay_scale = 1.4
session_overlay_opacity = 170
session_overlay_anchor = "TopLeft"
session_overlay_offset = [
    24.0,
    150.0,
]
session_overlay_display = "Compact"
layout_mode = false
