transparency = 150
ui_scale = 2.200000047683716
show_bots = true
window_size = [
    2560.0,
    1440.0,
]
anchor = "CenterRight"
monitor_index = 0
hotkey_kb = "Tab"
hotkey_ctrl = "Select"
hotkey_settings = "F1"
hotkey_toggle = false
show_stats = true
show_teammate_boost = true
teammate_boost_offset = 180.0
teammate_boost_horizontal_offset = 110.0
teammate_hud_scale = 2.200000047683716
